# This is a basic workflow to help you get started with Actions

name: test-sync-api

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

     
      - name: git account identity
        run:   git config --global user.email "cps-robot@yunify.com" && git config --global user.name "qingcloud-cps-robot"
        #run:   git config --global user.email "306085175@qq.com" && git config --global user.name "conggeqc"

      - name: clone java sdk    
        run: cd  /home/runner/work/ && git clone https://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@github.com/yunify/qingcloud-sdk-java.git
    
      - name: add date file
        run: cd /home/runner/work/qingcloud-sdk-java && touch date.txt 
     

      - name: cat  java sdk git config
        run: cd /home/runner/work/qingcloud-sdk-java/.git && cat config   
      

      #- name: branch to commit && push
      #  run: cd /home/runner/work/qingcloud-sdk-java && git branch api-specs-sync && git switch api-specs-sync && git add -A && git commit -m "from project qingcloud-api-specs ci" && git push --set-upstream origin api-specs-sync
  
      - name: upload branch 
        env:
          #robot  
          #GITHUB_TOKEN: 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
          #congge  
          #GITHUB_TOKEN: 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
          GITHUB_TOKEN: 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

        run: |
          sudo rm -rf  tmp.txt .git*
          git init
          git config user.name "qingcloud-cps-robot"
          git config user.email "cps-robot@yunify.com"          
          git add .
          git commit -m "Update api-specs-sync from project qingcloud-api-specs ci "
          git push --force --quiet https://$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@github.com/conggeqc/test.git HEAD:api-specs-sync
      
      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: java Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: branch api-specs-sync
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          #assignees: peter-evans
          #reviewers: peter-evans
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
        
        
     
      - name:  clone go sdk
        run: git clone https://github.com/yunify/qingcloud-sdk-go.git
      - name: snips go sdk api specs
        run: snips -f /home/runner/work/qingcloud-api-specs/qingcloud-api-specs/2013-08-30/swagger/api_v2.0.json -t ./qingcloud-sdk-go/template -o ./qingcloud-sdk-go/service/
      - name: push go sdk api specs
        #run: cd ./qingcloud-sdk-java && git branch api-specs-sync && git checkout api-specs-sync &&  git commit -m "from project qingcloud-api-specs ci" && git push  --set-upstream origin api-specs-sync
        run: echo push go sdk api specs 

     
      - name: clone ruby sdk
        run:  git clone https://github.com/yunify/qingcloud-sdk-ruby.git
      - name: snips ruby sdk api specs
        run: snips -f /home/runner/work/qingcloud-api-specs/qingcloud-api-specs/2013-08-30/swagger/api_v2.0.json -t ./qingcloud-sdk-ruby/template -o ./qingcloud-sdk-ruby/lib/qingcloud/sdk/service/
      - name: push ruby sdk api specs
        #run: cd ./qingcloud-sdk-java && git branch api-specs-sync &&  git commit -m "from project qingcloud-api-specs ci" && git push --set-upstream origin api-specs-sync
        run: echo push ruby sdk api specs 
   
